In [1]:
import numpy as np

In [2]:
print("numpy version:", np.__version__)

numpy version: 1.19.1


In [3]:
array1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [4]:
print(array1)
print(type(array1))
print(array1[0])
print(type(array1[0]))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
print(array1.shape)
print(type(array1.shape))

row, col = array1.shape
print("num of row:", row)
print("num of col:", col)

print(array1[0].shape)
print(type(array1[0].shape))
n_item = array1[0].shape[0]
print("num of item:", n_item)

(3, 4)
<class 'tuple'>
num of row: 3
num of col: 4
(4,)
<class 'tuple'>
num of item: 4


In [6]:
arr_zeros = np.zeros((4, 5))
print(arr_zeros, arr_zeros.shape)

print(np.zeros(5))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] (4, 5)
[0. 0. 0. 0. 0.]


In [7]:
arr_ones_2d = np.ones((4, 5))
print(arr_ones_2d, arr_ones_2d.shape, arr_ones_2d.dtype)
arr_ones_3d = np.ones((2, 2, 3), dtype=int)
print(arr_ones_3d, arr_ones_3d.shape, arr_ones_3d.dtype)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] (4, 5) float64
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]] (2, 2, 3) int64


In [8]:
arr_empty_2d = np.empty((2, 4))
arr_empty_3d = np.empty((2, 2, 2))
print(arr_empty_2d, arr_empty_2d.shape)

print(np.empty((1000, 1000)))
print(np.zeros((1000, 1000)))

[[-2.00000000e+000  2.00390263e+000  1.97626258e-323  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000 -2.00000000e+000  5.60610283e-309]] (2, 4)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [9]:
arr_arange_1d = np.arange(4)
print(arr_arange_1d, arr_arange_1d.shape, type(arr_arange_1d))

print(np.arange(1, step=.1))
print(np.arange(10, 5, -.1))

[0 1 2 3] (4,) <class 'numpy.ndarray'>
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[10.   9.9  9.8  9.7  9.6  9.5  9.4  9.3  9.2  9.1  9.   8.9  8.8  8.7
  8.6  8.5  8.4  8.3  8.2  8.1  8.   7.9  7.8  7.7  7.6  7.5  7.4  7.3
  7.2  7.1  7.   6.9  6.8  6.7  6.6  6.5  6.4  6.3  6.2  6.1  6.   5.9
  5.8  5.7  5.6  5.5  5.4  5.3  5.2  5.1]


In [10]:
mylist = [[1, 2, 3], [4, 5, 6]]
print(mylist, mylist[0], mylist[0][::2])

print(arr_empty_2d, arr_empty_2d[0], arr_empty_2d[0, ::2])
print(arr_empty_2d[:, ::2])
print(arr_empty_2d[:, ::-1])

print(arr_empty_3d)
print(arr_empty_3d[:, 0, :])
print(arr_empty_3d[::-1, 0, ::-1])

[[1, 2, 3], [4, 5, 6]] [1, 2, 3] [1, 3]
[[-2.00000000e+000  2.00390263e+000  1.97626258e-323  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000 -2.00000000e+000  5.60610283e-309]] [-2.00000000e+000  2.00390263e+000  1.97626258e-323  0.00000000e+000] [-2.e+000  2.e-323]
[[-2.e+000  2.e-323]
 [ 0.e+000 -2.e+000]]
[[ 0.00000000e+000  1.97626258e-323  2.00390263e+000 -2.00000000e+000]
 [ 5.60610283e-309 -2.00000000e+000  0.00000000e+000  0.00000000e+000]]
[[[-2.00000000e+000 -2.00390263e+000]
  [ 1.97626258e-323  0.00000000e+000]]

 [[ 0.00000000e+000  0.00000000e+000]
  [-2.00000000e+000  5.60610283e-309]]]
[[-2.         -2.00390263]
 [ 0.          0.        ]]
[[ 0.          0.        ]
 [-2.00390263 -2.        ]]


In [11]:
print(np.empty(4))
print(np.empty((1, 4)))

[ 0.          0.         -2.00390263 -2.        ]
[[ 0.          0.         -2.00390263 -2.        ]]


In [12]:
new_zeros = np.zeros((3, 3))
print(new_zeros)
print(array1)

print(np.append(array1, new_zeros))
print(np.append(array1, new_zeros, axis=1))
print(np.append(array1, arr_arange_1d[np.newaxis, :], axis=0))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.  0.  0.  0.  0.  0.  0.
  0.  0.  0.]
[[ 1.  2.  3.  4.  0.  0.  0.]
 [ 5.  6.  7.  8.  0.  0.  0.]
 [ 9. 10. 11. 12.  0.  0.  0.]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 0  1  2  3]]


In [13]:
mylist = [1, 2, 3]
print(mylist)
mylist.extend([1, 2, 3])
print(mylist)

[1, 2, 3]
[1, 2, 3, 1, 2, 3]


In [14]:
print(array1)
print(np.delete(array1, [0, 2], axis=1))
print(array1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  4]
 [ 6  8]
 [10 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
print(arr_empty_2d)
np.sort(arr_empty_2d, axis=1)

[[-2.00000000e+000  2.00390263e+000  1.97626258e-323  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000 -2.00000000e+000  5.60610283e-309]]


array([[-2.00000000e+000,  0.00000000e+000,  1.97626258e-323,
         2.00390263e+000],
       [-2.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         5.60610283e-309]])

In [16]:
print(arr_empty_2d.shape, arr_empty_2d.ndim, arr_empty_2d.size)
print(arr_empty_3d.shape, arr_empty_3d.ndim, arr_empty_3d.size)

(2, 4) 2 8
(2, 2, 2) 3 8


In [17]:
print(array1)
print(np.reshape(array1, [2, 6]))
print(np.reshape(array1, [2, 2, 3]))
print(np.reshape(array1, [4, 1, 3]))

# print(np.reshape(array1, (2, 7)))   # will throw error

print(array1.reshape(4, 1, 3))
print(array1.reshape(2, 2, 1, 3))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]]

 [[ 4  5  6]]

 [[ 7  8  9]]

 [[10 11 12]]]
[[[ 1  2  3]]

 [[ 4  5  6]]

 [[ 7  8  9]]

 [[10 11 12]]]
[[[[ 1  2  3]]

  [[ 4  5  6]]]


 [[[ 7  8  9]]

  [[10 11 12]]]]


In [18]:
print(array1[:, np.newaxis, :, np.newaxis, np.newaxis])
print(array1.reshape(3, 1, 4))
print(np.expand_dims(array1, axis=2))

[[[[[ 1]]

   [[ 2]]

   [[ 3]]

   [[ 4]]]]



 [[[[ 5]]

   [[ 6]]

   [[ 7]]

   [[ 8]]]]



 [[[[ 9]]

   [[10]]

   [[11]]

   [[12]]]]]
[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


In [19]:
print(array1)
even_number = array1 % 2 == 0
print(even_number)
print(array1[even_number])

print(np.where(array1 % 2 == 0, array1*10, array1))
print(np.where(array1 % 2 == 0, array1, 0))
print(np.argwhere(array1 % 2 == 0))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[False  True False  True]
 [False  True False  True]
 [False  True False  True]]
[ 2  4  6  8 10 12]
[[  1  20   3  40]
 [  5  60   7  80]
 [  9 100  11 120]]
[[ 0  2  0  4]
 [ 0  6  0  8]
 [ 0 10  0 12]]
[[0 1]
 [0 3]
 [1 1]
 [1 3]
 [2 1]
 [2 3]]


In [20]:
print(np.vstack(([0, 0, 0, 0], array1,)))
print(np.hstack((array1, [[0], [0], [0]])))
print(np.concatenate(
    [
        array1,
        [[0, 0, 0, 0]],
        [[1, 1, 1, 1]]
    ],
    axis=0
))
print(np.concatenate(
    [
        np.zeros((3, 3)),
        array1,
        np.zeros((3, 3)),
        np.ones((3, 5))
    ],
    axis=1
))

[[ 0  0  0  0]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  0]
 [ 5  6  7  8  0]
 [ 9 10 11 12  0]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 0  0  0  0]
 [ 1  1  1  1]]
[[ 0.  0.  0.  1.  2.  3.  4.  0.  0.  0.  1.  1.  1.  1.  1.]
 [ 0.  0.  0.  5.  6.  7.  8.  0.  0.  0.  1.  1.  1.  1.  1.]
 [ 0.  0.  0.  9. 10. 11. 12.  0.  0.  0.  1.  1.  1.  1.  1.]]


In [21]:
[1, 2, 3] + [4, 5, 6], [1, 2, 3] * 2

([1, 2, 3, 4, 5, 6], [1, 2, 3, 1, 2, 3])

In [22]:
array1_0 = array1[0]
print(array1_0)

print(array1_0 + array1_0)
print(array1_0 - array1_0)
print(array1_0 * 10)
print(array1_0 * 10 + array1_0)
print(array1_0 ** 3)
print(array1_0 / 2)
print(array1_0 // 2)

print(array1 * array1_0)

[1 2 3 4]
[2 4 6 8]
[0 0 0 0]
[10 20 30 40]
[11 22 33 44]
[ 1  8 27 64]
[0.5 1.  1.5 2. ]
[0 1 1 2]
[[ 1  4  9 16]
 [ 5 12 21 32]
 [ 9 20 33 48]]


In [23]:
print(array1)
print(array1.sum())
print(array1.sum(axis=0))
print(array1.sum(axis=0, keepdims=True))
print(array1.sum(axis=1, keepdims=True))
print(array1.max())
print(array1.max(axis=1))
print(array1.max(axis=1, keepdims=True))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
78
[15 18 21 24]
[[15 18 21 24]]
[[10]
 [26]
 [42]]
12
[ 4  8 12]
[[ 4]
 [ 8]
 [12]]


In [24]:
print(array1 * array1)
print(array1)
print(array1.T)
print(array1.transpose())
print(np.dot(array1, array1.T))
print(np.dot(array1.T, array1))
print(array1.T.dot(array1))

np.matmul(array1, array1.T)

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
[[107 122 137 152]
 [122 140 158 176]
 [137 158 179 200]
 [152 176 200 224]]
[[107 122 137 152]
 [122 140 158 176]
 [137 158 179 200]
 [152 176 200 224]]


array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [25]:
arr2 = np.array([[1, 2], [3, 4]])
arr3 = np.array([[3, 4], [5, 6]])
print(arr2)
print(arr3)

print(arr2.dot(arr3))


[[1 2]
 [3 4]]
[[3 4]
 [5 6]]
[[13 16]
 [29 36]]
